const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");

const root = path.resolve(__dirname, "..");
const data = JSON.parse(fs.readFileSync(path.join(root, "data/russia-cities.json"), "utf8"));
const populationData = JSON.parse(fs.readFileSync(path.join(root, "data/russia-city-populations.json"), "utf8"));
const populationByCity = new Map(populationData.cities.map((city) => [`${city.name}::${city.region}`, city.population]));
const dataWithPopulation = { ...data, cities: data.cities.map((city) => populationByCity.has(`${city.name}::${city.region}`) ? { ...city, population: populationByCity.get(`${city.name}::${city.region}`) } : city) };
const source = fs.readFileSync(path.join(root, "tools/minus-goroda-yandex-direct/minus-cities.js"), "utf8");
const html = fs.readFileSync(path.join(root, "tools/minus-goroda-yandex-direct/index.html"), "utf8");
const context = { window: {}, document: { querySelector: () => null } };
vm.runInNewContext(fs.readFileSync(path.join(root, "tools/minus-goroda-yandex-direct/minus-cities.js"), "utf8"), context);
const { buildResult, toCsv, limits, normalize, exceedsLimit } = context.window.NaklikayMinusCities;
const byName = (name) => data.cities.find((city) => city.name === name);
const rostov = byName("Ростов-на-Дону");
assert.ok(rostov && rostov.region === "Ростовская область", "Ростов-на-Дону must be present in the local database");
assert.equal(data.regions.some((region) => region.name === "Ростовская область"), true, "Ростовская область must be present");
assert.equal(new Set(data.cities.map((city) => `${context.window.NaklikayMinusCities.normalize(city.name)}\u0000${context.window.NaklikayMinusCities.normalize(city.region)}`)).size, data.cities.length, "database must not contain duplicate city-region records");
const full = buildResult(data, [], false);
assert.equal(full.cities.length, new Set(data.cities.map((city) => normalize(city.name))).size, "full result must have unique city names");
assert.equal(full.regions.length, 0, "regions must be disabled by default");
assert.equal(full.items.length, full.cities.length, "city-only result must contain every displayed city");
assert.equal(full.text.includes("\n\n"), false, "full result must not have empty lines");
assert.equal(full.characters, full.text.replace(/\s/g, "").length, "character count must ignore whitespace");
assert.equal(populationData.matchedCities, populationData.cities.length, "population metadata must match the number of records");
assert.equal(new Set(populationData.cities.map((city) => `${city.name}::${city.region}`)).size, populationData.cities.length, "population records must be unique");
assert.ok(populationData.cities.every((city) => Number.isFinite(city.population) && city.population >= 0), "population records must contain valid values");
const citiesFromThirtyThousand = buildResult(dataWithPopulation, [], false, 30000);
assert.ok(citiesFromThirtyThousand.cities.length > 0 && citiesFromThirtyThousand.cities.length < full.cities.length, "population filter must reduce the city list");
assert.ok(citiesFromThirtyThousand.cities.every((city) => city.population >= 30000), "population filter must exclude cities below the threshold and cities without data");
const populationBoundary = buildResult({ cities: [{ name: "Ровно", region: "Тест", population: 30000 }, { name: "Меньше", region: "Тест", population: 29999 }, { name: "Нет данных", region: "Тест" }], regions: [] }, [], false, 30000);
assert.deepEqual(Array.from(populationBoundary.cities, (city) => city.name), ["Ровно"], "population threshold must be inclusive and exclude unknown values");
const fullWithRegions = buildResult(data, [], true);
const fullWithRegionNames = fullWithRegions.items.map((item) => normalize(item.name));
assert.equal(new Set(fullWithRegionNames).size, fullWithRegions.items.length, "city and region output must not contain duplicate names");
assert.equal(fullWithRegions.items.length, fullWithRegions.cities.length + fullWithRegions.regions.length, "total count must include cities and unique regions");
assert.ok(fullWithRegions.regions.length > 0, "enabled setting must add region names");
assert.ok(fullWithRegions.characters > full.characters, "enabled setting must increase the character count");
["Москва", "Санкт-Петербург", "Севастополь"].forEach((name) => assert.equal(fullWithRegions.items.filter((item) => normalize(item.name) === normalize(name)).length, 1, `${name} must not be duplicated as a city and region`));
const selectedCity = buildResult(data, [{ kind: "city", key: "city", name: "Ростов-на-Дону", label: "Ростов-на-Дону" }], false);
assert.equal(selectedCity.text.includes("Ростов-на-Дону"), false, "selected city must not be exported");
const selectedRegion = buildResult(data, [{ kind: "region", key: "region", name: "Ростовская область", label: "Ростовская область" }], false);
assert.equal(selectedRegion.cities.some((city) => city.region === "Ростовская область"), false, "selected region cities must not be exported");
const selectedRegionWithRegions = buildResult(data, [{ kind: "region", key: "region", name: "Ростовская область", label: "Ростовская область" }], true);
assert.equal(selectedRegionWithRegions.items.some((item) => item.name === "Ростовская область"), false, "selected region name must not be exported");
const multiRegion = buildResult(data, [{ kind: "region", key: "rostov", name: "Ростовская область", label: "Ростовская область" }, { kind: "region", key: "moscow", name: "Москва", label: "Москва" }], true);
assert.equal(multiRegion.items.some((item) => item.name === "Москва"), false, "selected federal city must not be exported as a region");
const selectedMoscowCity = buildResult(data, [{ kind: "city", key: "moscow-city", name: "Москва", label: "Москва" }], true);
assert.equal(selectedMoscowCity.items.some((item) => item.name === "Москва"), false, "selected city must not return through a region with the same name");
assert.ok(toCsv(full.items, false).startsWith('"Город"\r\n'), "CSV must have a City header");
assert.equal(toCsv(fullWithRegions.items, true).split("\r\n").length, fullWithRegions.items.length + 1, "CSV must contain the same complete result plus its header");
assert.deepEqual({ ...limits }, { group: 4096, campaign: 20000 }, "Yandex Direct limits must be available to the interface");
assert.equal(exceedsLimit(4096, limits.group), false, "group limit must allow exactly 4096 characters");
assert.equal(exceedsLimit(4097, limits.group), true, "group limit must reject more than 4096 characters");
assert.equal(exceedsLimit(20000, limits.campaign), false, "campaign limit must allow exactly 20000 characters");
assert.equal(exceedsLimit(20001, limits.campaign), true, "campaign limit must reject more than 20000 characters");
assert.ok(source.includes("preview.textContent = result.text"), "preview must show the complete generated result");
assert.equal(source.includes("slice(0, 30)"), false, "preview must not be limited to 30 lines");
assert.ok(html.includes("Исключать запросы с названиями регионов"), "region setting must describe its advertising effect clearly");
assert.ok(html.includes("При включении в список добавятся области, края, республики и округа, например «Московская область». Выбранные вами регионы не добавятся."), "region setting must explain which names will be added");
assert.ok(html.includes("Оставить в списке только крупные города"), "population filter must have a clear label");
assert.ok(html.includes("По данным Росстата на 1 января 2025 года."), "population filter must name its source date");
assert.ok(html.includes("data-minus-population-toggle") && html.includes("data-minus-population"), "population filter controls must be available");
assert.ok(source.includes('fetch("../../data/russia-city-populations.json"'), "population data must be loaded from the local database");
assert.ok(html.includes("data-minus-group-limit") && html.includes("data-minus-campaign-limit"), "both Yandex Direct limits must be visible");
assert.ok(source.includes('renderLimit(groupLimit, "Для группы объявлений в Яндекс Директе"'), "group limit must name Yandex Direct");
assert.ok(source.includes('renderLimit(campaignLimit, "Для кампании в Яндекс Директе"'), "campaign limit must name Yandex Direct");
assert.equal(source.includes("\\u0000"), false, "chip keys must be valid HTML attribute values");
console.log(`minus-cities: ${data.cities.length} city records, ${full.cities.length} unique cities, ${fullWithRegions.regions.length} unique regions`);
