const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");

const root = path.resolve(__dirname, "..");
const data = JSON.parse(fs.readFileSync(path.join(root, "data/russia-cities.json"), "utf8"));
const source = fs.readFileSync(path.join(root, "tools/minus-goroda-yandex-direct/minus-cities.js"), "utf8");
const context = { window: {}, document: { querySelector: () => null } };
vm.runInNewContext(fs.readFileSync(path.join(root, "tools/minus-goroda-yandex-direct/minus-cities.js"), "utf8"), context);
const { buildResult, toCsv } = context.window.NaklikayMinusCities;
const byName = (name) => data.cities.find((city) => city.name === name);
const rostov = byName("Ростов-на-Дону");
assert.ok(rostov && rostov.region === "Ростовская область", "Ростов-на-Дону must be present in the local database");
assert.equal(data.regions.some((region) => region.name === "Ростовская область"), true, "Ростовская область must be present");
assert.equal(new Set(data.cities.map((city) => `${context.window.NaklikayMinusCities.normalize(city.name)}\u0000${context.window.NaklikayMinusCities.normalize(city.region)}`)).size, data.cities.length, "database must not contain duplicate city-region records");
const full = buildResult(data, [], false);
assert.equal(full.cities.length, new Set(data.cities.map((city) => context.window.NaklikayMinusCities.normalize(city.name))).size, "full result must have unique city names");
assert.equal(full.text.includes("\n\n"), false, "full result must not have empty lines");
assert.equal(full.characters, full.text.replace(/\s/g, "").length, "character count must ignore whitespace");
const selectedCity = buildResult(data, [{ kind: "city", key: "city", name: "Ростов-на-Дону", label: "Ростов-на-Дону" }], false);
assert.equal(selectedCity.text.includes("Ростов-на-Дону"), false, "selected city must not be exported");
const selectedRegion = buildResult(data, [{ kind: "region", key: "region", name: "Ростовская область", label: "Ростовская область" }], false);
assert.equal(selectedRegion.cities.some((city) => city.region === "Ростовская область"), false, "selected region cities must not be exported");
const multiRegion = buildResult(data, [{ kind: "region", key: "rostov", name: "Ростовская область", label: "Ростовская область" }, { kind: "region", key: "moscow", name: "Москва", label: "Москва" }], true);
assert.equal(multiRegion.items.some((item) => item.name === "Москва"), false, "selected federal city must not be exported as a region");
assert.ok(toCsv(full.items, false).startsWith('"Город"\r\n'), "CSV must have a City header");
assert.equal(source.includes("\\u0000"), false, "chip keys must be valid HTML attribute values");
console.log(`minus-cities: ${data.cities.length} city records, ${full.cities.length} unique output names`);
