const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const vm = require("node:vm");

const root = path.resolve(__dirname, "..");
const data = JSON.parse(fs.readFileSync(path.join(root, "data/russia-cities.json"), "utf8"));
const source = fs.readFileSync(path.join(root, "tools/minus-goroda-yandex-direct/minus-cities.js"), "utf8");
const html = fs.readFileSync(path.join(root, "tools/minus-goroda-yandex-direct/index.html"), "utf8");
const context = { window: {}, document: { querySelector: () => null } };
vm.runInNewContext(fs.readFileSync(path.join(root, "tools/minus-goroda-yandex-direct/minus-cities.js"), "utf8"), context);
const { buildResult, toCsv, limits, normalize, exceedsLimit } = context.window.NaklikayMinusCities;
const byName = (name) => data.cities.find((city) => city.name === name);
const rostov = byName("Ростов-на-Дону");
assert.ok(rostov && rostov.region === "Ростовская область", "Ростов-на-Дону must be present in the local database");
assert.equal(data.regions.some((region) => region.name === "Ростовская область"), true, "Ростовская область must be present");
assert.equal(new Set(data.cities.map((city) => `${context.window.NaklikayMinusCities.normalize(city.name)}\u0000${context.window.NaklikayMinusCities.normalize(city.region)}`)).size, data.cities.length, "database must not contain duplicate city-region records");
const full = buildResult(data, [], false);
assert.equal(full.cities.length, new Set(data.cities.map((city) => normalize(city.name))).size, "full result must have unique city names");
assert.equal(full.regions.length, 0, "regions must be disabled by default");
assert.equal(full.items.length, full.cities.length, "city-only result must contain every displayed city");
assert.equal(full.text.includes("\n\n"), false, "full result must not have empty lines");
assert.equal(full.characters, full.text.replace(/\s/g, "").length, "character count must ignore whitespace");
const fullWithRegions = buildResult(data, [], true);
const fullWithRegionNames = fullWithRegions.items.map((item) => normalize(item.name));
assert.equal(new Set(fullWithRegionNames).size, fullWithRegions.items.length, "city and region output must not contain duplicate names");
assert.equal(fullWithRegions.items.length, fullWithRegions.cities.length + fullWithRegions.regions.length, "total count must include cities and unique regions");
assert.ok(fullWithRegions.regions.length > 0, "enabled setting must add region names");
assert.ok(fullWithRegions.characters > full.characters, "enabled setting must increase the character count");
["Москва", "Санкт-Петербург", "Севастополь"].forEach((name) => assert.equal(fullWithRegions.items.filter((item) => normalize(item.name) === normalize(name)).length, 1, `${name} must not be duplicated as a city and region`));
const selectedCity = buildResult(data, [{ kind: "city", key: "city", name: "Ростов-на-Дону", label: "Ростов-на-Дону" }], false);
assert.equal(selectedCity.text.includes("Ростов-на-Дону"), false, "selected city must not be exported");
const selectedRegion = buildResult(data, [{ kind: "region", key: "region", name: "Ростовская область", label: "Ростовская область" }], false);
assert.equal(selectedRegion.cities.some((city) => city.region === "Ростовская область"), false, "selected region cities must not be exported");
const selectedRegionWithRegions = buildResult(data, [{ kind: "region", key: "region", name: "Ростовская область", label: "Ростовская область" }], true);
assert.equal(selectedRegionWithRegions.items.some((item) => item.name === "Ростовская область"), false, "selected region name must not be exported");
const multiRegion = buildResult(data, [{ kind: "region", key: "rostov", name: "Ростовская область", label: "Ростовская область" }, { kind: "region", key: "moscow", name: "Москва", label: "Москва" }], true);
assert.equal(multiRegion.items.some((item) => item.name === "Москва"), false, "selected federal city must not be exported as a region");
const selectedMoscowCity = buildResult(data, [{ kind: "city", key: "moscow-city", name: "Москва", label: "Москва" }], true);
assert.equal(selectedMoscowCity.items.some((item) => item.name === "Москва"), false, "selected city must not return through a region with the same name");
assert.ok(toCsv(full.items, false).startsWith('"Город"\r\n'), "CSV must have a City header");
assert.equal(toCsv(fullWithRegions.items, true).split("\r\n").length, fullWithRegions.items.length + 1, "CSV must contain the same complete result plus its header");
assert.deepEqual({ ...limits }, { group: 4096, campaign: 20000 }, "Yandex Direct limits must be available to the interface");
assert.equal(exceedsLimit(4096, limits.group), false, "group limit must allow exactly 4096 characters");
assert.equal(exceedsLimit(4097, limits.group), true, "group limit must reject more than 4096 characters");
assert.equal(exceedsLimit(20000, limits.campaign), false, "campaign limit must allow exactly 20000 characters");
assert.equal(exceedsLimit(20001, limits.campaign), true, "campaign limit must reject more than 20000 characters");
assert.ok(source.includes("preview.textContent = result.text"), "preview must show the complete generated result");
assert.equal(source.includes("slice(0, 30)"), false, "preview must not be limited to 30 lines");
assert.ok(html.includes("Добавить названия остальных регионов"), "region setting must describe the result clearly");
assert.ok(html.includes("К городам добавятся области, края, республики и округа, кроме выбранных вами регионов."), "region setting must explain which names will be added");
assert.ok(html.includes("data-minus-group-limit") && html.includes("data-minus-campaign-limit"), "both Yandex Direct limits must be visible");
assert.equal(source.includes("\\u0000"), false, "chip keys must be valid HTML attribute values");
console.log(`minus-cities: ${data.cities.length} city records, ${full.cities.length} unique cities, ${fullWithRegions.regions.length} unique regions`);
